title:
  de: Projekt
  en: Project

columns:
  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
          subtitle:
            label:
              de: Untertitel
              en: Subtitle
            type: text
            required: true
            width: 1/2
          thumbnail:
            label:
              de: Titelbild
              en: Cover Image
            type: files
            query: page.files.template("image")
            uploads:
              template: image
            multiple: false
            translate: false
            required: true
            width: 1/2
          galleryType:
            label:
              de: Galerietyp
              en: Gallery Type
            type: toggles
            default: slider
            options:
              - value: slider
                text: Slider
                icon: badge
              - value: masonry
                text: Masonry
                icon: grid
            translate: false
          galleryHeight:
            label:
              de: Galeriehöhe
              en: Gallery Height
            type: toggles
            default: loose
            options:
              - value: tight
                text:
                  de: Eng
                  en: Tight
              - value: normal
                text:
                  de: Normal
                  en: Normal
              - value: loose
                text:
                  de: Locker
                  en: Loose
            translate: false
            when:
              galleryType: slider
      images: sections/images
      files: sections/files

  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          gallery:
            label:
              de: Galerie
              en: Gallery
            type: files
            layout: cards
            translate: false
            image:
              back: white
          text: fields/blocks
