title:
  de: Projekt
  en: Project

tabs:
  article:
    label:
      en: Page
      de: Seite
    icon: draft
    columns:
      - width: 1/2
        sections:
          meta:
            type: fields
            fields:
              subtitle:
                label:
                  de: Untertitel
                  en: Subtitle
                type: text
                required: true
                width: 1/2
              thumbnail:
                label:
                  de: Titelbild
                  en: Cover Image
                type: files
                query: page.files.template(["image", "blocks/image"])
                uploads:
                  template: image
                multiple: false
                translate: false
                required: true
                width: 1/2

      - width: 1/2
        sections:
          galleryOptions:
            type: fields
            fields:
              galleryType:
                label:
                  de: Galerietyp
                  en: Gallery Type
                type: toggles
                default: slider
                options:
                  - value: slider
                    text: Slider
                  - value: masonry
                    text: Masonry
                translate: false
                width: 1/2
              galleryHeight:
                label:
                  de: Galeriehöhe
                  en: Gallery Height
                type: select
                default: loose
                options:
                  - value: tight
                    text:
                      de: Eng
                      en: Tight
                  - value: normal
                    text:
                      de: Normal
                      en: Normal
                  - value: loose
                    text:
                      de: Locker
                      en: Loose
                translate: false
                when:
                  galleryType: slider
                width: 1/2

      - width: 1/2
        sections:
          text: sections/text

      - width: 1/2
        sections:
          gallery:
            type: fields
            fields:
              gallery:
                label:
                  de: Galerie
                  en: Gallery
                type: files
                query: page.files.template(["image", "blocks/image"])
                uploads:
                  template: image
                translate: false
                image:
                  back: white
          contentTranslator: sections/content-translator

  images: tabs/images
  files: tabs/files
