title:
  de: Projekt
  en: Project

buttons:
  - open
  - settings
  - copilot
  - languages
  - status

tabs:
  content:
    label:
      de: Inhalt
      en: Content
    icon: draft
    columns:
      - width: 2/3
        sections:
          gallery:
            type: fields
            fields:
              gallery:
                label:
                  de: Galerie
                  en: Gallery
                type: files
                layout: cards
                query: page.files.template(["image", "blocks/image"])
                uploads:
                  template: image
                translate: false
                image:
                  cover: true
                  ratio: 1/1
                  back: white
          text: sections/text

      - width: 1/3
        sections:
          meta:
            type: fields
            fields:
              subtitle:
                label:
                  de: Untertitel
                  en: Subtitle
                type: text
                required: true
              thumbnail:
                extends: fields/thumbnail
                required: true
              galleryHeight:
                label:
                  de: Galeriehöhe
                  en: Gallery Height
                type: select
                default: loose
                options:
                  - value: tight
                    text:
                      de: Niedrig
                      en: Short
                  - value: loose
                    text:
                      de: Hoch
                      en: Tall
                translate: false
              separator:
                type: line
              details:
                label:
                  de: Infobox
                  en: Infobox
                type: structure
                fields:
                  label:
                    label: Label
                    type: text
                    width: 1/2
                  value:
                    label:
                      de: Wert
                      en: Value
                    type: writer
                    inline: true
                    width: 1/2
                    required: true

  seo:
    label: SEO
    icon: search
    columns:
      - width: 2/3
        sections:
          seoFields:
            type: fields
            fields:
              description:
                extends: fields/description

      - width: 1/3
        sections:
          serpPreview: sections/serp-preview

  images: tabs/images
  files: tabs/files
