title:
  de: Projekt
  en: Project

columns:
  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
          subtitle:
            label:
              de: Untertitel
              en: Subtitle
            type: text
            required: true
            width: 1/2
          thumbnail:
            label:
              de: Titelbild
              en: Cover Image
            type: files
            query: page.files.template('image')
            uploads:
              template: image
            multiple: false
            translate: false
            required: true
            width: 1/2
          galleryHeight:
            label:
              de: Galeriehöhe
              en: Gallery Height
            type: select
            default: loose
            options:
              tight:
                de: Eng
                en: Tight
              normal:
                de: Normal
                en: Normal
              loose:
                de: Locker
                en: Loose
            translate: false
      images: sections/images
      files: sections/files

  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          gallery:
            label:
              de: Galerie
              en: Gallery
            type: files
            layout: cards
            translate: false
            image:
              back: white
          text: fields/blocks
