type: fields
fields:
  customTitle:
    label:
      de: Titel (Überschreiben)
      en: Title (Override)
    type: text
    icon: title
    placeholder: "{{ page.title }} – {{ site.title }}"
    help:
      de: Optionaler abweichender Titel für Suchmaschinen.
      en: Optional different title for search engines.
  description:
    label:
      de: Beschreibung (Überschreiben)
      en: Description (Override)
    type: textarea
    buttons: false
    help:
      de: Eine kurze Beschreibung für Suchmaschinen.
      en: A short description for search engines.
  thumbnail:
    label:
      de: Vorschaubild
      en: Thumbnail
    type: files
    query: page.files.template("image")
    uploads:
      template: image
    multiple: false
    translate: false
