import * as fsp from "node:fs/promises";
import * as path from "node:path";
import process from "node:process";
import { formatHex, parse } from "culori";
import { colors, palette } from "../src/tokens.ts";

interface Token {
  oklch: string;
  hex: string;
}

interface Naming {
  /** Custom property namespace: `un-color` for our own groups, `tw-color` for copied ones. */
  namespace: string;
  /** Key that also gets an unsuffixed alias, such as `--un-color-primary`. */
  aliasedKey?: string;
}

/** How each group in `src/tokens.ts` turns into custom property names. */
const NAMING: Record<string, Naming> = {
  primary: { namespace: "un-color", aliasedKey: "500" },
  secondary: { namespace: "un-color", aliasedKey: "500" },
  stone: { namespace: "tw-color" },
  background: { namespace: "un-color" },
};

const projectRoot = path.resolve(import.meta.dirname, "..");
const outDir = path.resolve(projectRoot, "src/generated");
const jsonFile = path.resolve(outDir, "tokens.json");
const cssFile = path.resolve(outDir, "tokens.css");

await fsp.mkdir(outDir, { recursive: true });
await Promise.all([
  fsp.writeFile(jsonFile, buildJson()),
  fsp.writeFile(cssFile, buildCss()),
]);

process.stdout.write(
  `Wrote ${path.relative(projectRoot, jsonFile)} and ${path.relative(projectRoot, cssFile)}\n`,
);

function buildJson(): string {
  const tokens = {
    palette: toTokenGroups(palette),
    colors: toTokenGroups(colors),
  };

  // Matches Prettier's JSON output, so the committed file survives `format:check`.
  return `${JSON.stringify(tokens, undefined, 2)}\n`;
}

function buildCss(): string {
  const blocks = Object.entries({ ...palette, ...colors }).map(
    ([name, values]) => declareGroup(name, values),
  );

  return `/* Generated by \`scripts/build-tokens.ts\` from \`src/tokens.ts\`. Do not edit. */
@layer foundations {
  :root {
${blocks.join("\n\n")}
  }
}
`;
}

function toTokenGroups(
  groups: Record<string, Record<string, string>>,
): Record<string, Record<string, Token>> {
  return Object.fromEntries(
    Object.entries(groups).map(([name, values]) => [name, toTokens(values)]),
  );
}

function toTokens(values: Record<string, string>): Record<string, Token> {
  return Object.fromEntries(
    Object.entries(values).map(([key, oklch]) => [key, toToken(oklch)]),
  );
}

function declareGroup(name: string, values: Record<string, string>): string {
  const naming = NAMING[name];

  if (!naming) {
    throw new Error(`Group "${name}" has no entry in \`NAMING\`.`);
  }

  const lines: string[] = [];

  if (naming.aliasedKey !== undefined) {
    const aliased = values[naming.aliasedKey];

    if (!aliased) {
      throw new Error(
        `Group "${name}" has no key "${naming.aliasedKey}" to alias.`,
      );
    }

    lines.push(declareProperty(`${naming.namespace}-${name}`, aliased));
  }

  for (const [key, oklch] of Object.entries(values)) {
    lines.push(declareProperty(`${naming.namespace}-${name}-${key}`, oklch));
  }

  return lines.join("\n");
}

function declareProperty(property: string, oklch: string): string {
  return `    --${property}: ${oklch}; /* ${toToken(oklch).hex} */`;
}

function toToken(oklch: string): Token {
  const color = parse(oklch);
  const hex = color && formatHex(color);

  if (!hex) {
    throw new Error(`Cannot convert color to hex: ${oklch}`);
  }

  return { oklch, hex };
}
