import * as fsp from "node:fs/promises";
import * as path from "node:path";
import process from "node:process";
import { formatHex, parse } from "culori";
import { colors, palette } from "../src/tokens.ts";

interface Token {
  oklch: string;
  hex: string;
}

interface PropertyNaming {
  /** Custom property namespace: `un-color` for our own groups, `tw-color` for copied ones. */
  namespace: string;
  /**
   * Key whose value also becomes the unsuffixed property, such as
   * `--un-color-primary`. Matches the `DEFAULT` entry in `uno.config.ts`.
   */
  defaultKey?: string;
}

/** How each group in `src/tokens.ts` turns into custom property names. */
const PROPERTY_NAMING: Record<string, PropertyNaming> = {
  primary: { namespace: "un-color", defaultKey: "500" },
  secondary: { namespace: "un-color", defaultKey: "500" },
  stone: { namespace: "tw-color" },
  background: { namespace: "un-color" },
};

const projectRoot = path.resolve(import.meta.dirname, "..");
const outDir = path.resolve(projectRoot, "src/generated");
const jsonFile = path.resolve(outDir, "tokens.json");
const cssFile = path.resolve(outDir, "tokens.css");

await fsp.mkdir(outDir, { recursive: true });
await Promise.all([
  fsp.writeFile(jsonFile, buildJson()),
  fsp.writeFile(cssFile, buildCss()),
]);

process.stdout.write(
  `Wrote ${path.relative(projectRoot, jsonFile)} and ${path.relative(projectRoot, cssFile)}\n`,
);

function buildJson(): string {
  const tokens = {
    palette: toTokenGroups(palette),
    colors: toTokenGroups(colors),
  };

  // Matches Prettier's JSON output, so the committed file survives `format:check`.
  return `${JSON.stringify(tokens, undefined, 2)}\n`;
}

function buildCss(): string {
  const groupDeclarations = Object.entries({ ...palette, ...colors }).map(
    ([groupName, values]) => declareGroup(groupName, values),
  );

  return `/* Generated by \`scripts/build-tokens.ts\` from \`src/tokens.ts\`. Do not edit. */
@layer foundations {
  :root {
${groupDeclarations.join("\n\n")}
  }
}
`;
}

function toTokenGroups(
  groups: Record<string, Record<string, string>>,
): Record<string, Record<string, Token>> {
  return Object.fromEntries(
    Object.entries(groups).map(([groupName, values]) => [
      groupName,
      toTokens(values),
    ]),
  );
}

function toTokens(values: Record<string, string>): Record<string, Token> {
  return Object.fromEntries(
    Object.entries(values).map(([key, oklch]) => [key, toToken(oklch)]),
  );
}

function declareGroup(
  groupName: string,
  values: Record<string, string>,
): string {
  const naming = PROPERTY_NAMING[groupName];

  if (!naming) {
    throw new Error(
      `Group "${groupName}" has no entry in \`PROPERTY_NAMING\`.`,
    );
  }

  const lines: string[] = [];

  if (naming.defaultKey !== undefined) {
    const defaultValue = values[naming.defaultKey];

    if (!defaultValue) {
      throw new Error(
        `Group "${groupName}" has no key "${naming.defaultKey}" to use as its default.`,
      );
    }

    lines.push(
      declareProperty(`${naming.namespace}-${groupName}`, defaultValue),
    );
  }

  for (const [key, oklch] of Object.entries(values)) {
    lines.push(
      declareProperty(`${naming.namespace}-${groupName}-${key}`, oklch),
    );
  }

  return lines.join("\n");
}

function declareProperty(propertyName: string, oklch: string): string {
  return `    --${propertyName}: ${oklch}; /* ${toToken(oklch).hex} */`;
}

function toToken(oklch: string): Token {
  const color = parse(oklch);
  const hex = color && formatHex(color);

  if (!hex) {
    throw new Error(`Cannot convert color to hex: ${oklch}`);
  }

  return { oklch, hex };
}
