#!/usr/bin/env php
<?php

require dirname(__DIR__) . '/public/bootstrap.php';

echo "\033[32mGenerating sitemap…\033[0m\n";

\KirbyExtended\SiteMeta::sitemap();

echo "\033[32m✓\033[0m Successfully indexed and cached sitemap.\n";
