import fg from "fast-glob";
import { readFile, writeFile } from "fs/promises";
import { createGenerator } from "unocss";
import { createConfig } from "../unocss.config";
import { white, green, dim } from "colorette";
import { watch } from "chokidar";

const distPath = "src/styles/uno.css";
const watchPaths = "site/{snippets,templates}/**/*";
const cache = new Map<string, string>();
const mode = process.env.NODE_ENV as "development" | "production" | undefined;

async function main() {
  console.log(
    green(
      mode === "production"
        ? "building UnoCSS for production..."
        : "starting UnoCSS in watch mode..."
    )
  );

  const config = createConfig();
  const uno = createGenerator({}, config);
  const files = await fg(watchPaths);

  await Promise.all(
    files.map(async (file) => {
      const content = await readFile(file, "utf8");
      cache.set(file, content);
    })
  );

  const generate = async () => {
    const { css, matched } = await uno.generate([...cache].join("\n"));
    await writeFile(distPath, `/* generated by unocss */\n${css}`);

    if (mode === "production") {
      console.log(
        `${green("✓")} ${[...matched].length} UnoCSS utilities generated.\n`
      );
    }
  };

  if (mode !== "production") {
    const watcher = watch(files, {
      ignoreInitial: true,
      ignorePermissionErrors: true,
    });

    console.log(
      "watching for changes in " +
        dim(Array.isArray(watchPaths) ? watchPaths.join(", ") : watchPaths)
    );

    watcher.on("all", async (type, file) => {
      console.log(green(`${type}:`) + " " + white(dim(file)));
      cache.set(file, await readFile(file, "utf8"));
      await generate();
    });
  }

  await generate();
}

main().catch(() => process.exit(1));
