title:
  de: Seite
  en: Site

tabs:
  dashboard:
    label:
      de: Übersicht
      en: Dashboard
    icon: paragraph
    columns:
      - width: 1/2
        sections:
          drafts:
            extends: sections/articles
            headline:
              de: Artikelentwürfe
              en: Article Drafts
            status: draft
          published:
            extends: sections/articles
            headline:
              de: Veröffentlichte Artikel
              en: Published Articles
            status: published
            limit: 10
            layout: cards
            size: tiny

      - width: 1/2
        sections:
          pages:
            type: pages
            headline:
              de: Seiten
              en: Pages
            status: all
            create: default
            info: "/{{ page.slug }}"
            image:
              query: page.thumbnail.toFile
              back: "#C9787C"
              cover: true

  settings:
    label:
      de: Einstellungen
      en: Settings
    icon: settings
    columns:
      - width: 1/2
        sections:
          content:
            type: fields
            fields:
              popularArticles:
                label:
                  de: Beliebte Artikel
                  en: Popular Articles
                type: pages
                query: kirby.page('blog')
                translate: false
              footerPages:
                label:
                  de: Fußzeilenlinks
                  en: Footer Pages
                type: pages
                translate: false

      - width: 1/2
        sections:
          meta:
            extends: sections/meta
            type: fields
            fields:
              thumbnail:
                query: kirby.page('photography').files.template('image')
                uploads:
                  parent: kirby.page('photography')
                  template: image
