title:
  de: Seite
  en: Site

buttons:
  - copilot
  - open
  - preview
  - languages

tabs:
  dashboard:
    label:
      de: Struktur
      en: Structure
    icon: sitemap
    columns:
      - width: 2/3
        sections:
          articles:
            extends: sections/articles
            label:
              de: Artikel
              en: Articles
            layout: table
            search: true
            columns:
              published:
                label:
                  de: Veröffentlicht
                  en: Published
                value: '{{ page.published.toDate("dd.MM.Y") }}'
                width: 1/4

      - width: 1/3
        sections:
          pages:
            type: pages
            label:
              de: Seiten
              en: Pages
            status: all
            create: default
            info: "/{{ page.slug }}"
            image:
              query: page.thumbnail.toFile
              cover: true
              back: "#89937A"

  info:
    label:
      de: Informationen
      en: Information
    icon: info
    columns:
      - width: 1/2
        sections:
          content:
            type: fields
            fields:
              headlineContent:
                label:
                  de: Inhalt
                  en: Content
                type: headline
              popularArticles:
                label:
                  de: Beliebte Artikel
                  en: Popular Articles
                type: pages
                query: kirby.page("blog")
                image:
                  query: page.thumbnail.toFile
                  cover: true
                  back: white
                translate: false
              headlineFooter:
                label:
                  de: Fußzeile
                  en: Footer
                type: headline
              footerLinks:
                label: Links
                type: structure
                fields:
                  category:
                    label:
                      de: Kategorie
                      en: Category
                    type: text
                  title:
                    label:
                      de: Titel
                      en: Title
                    type: text
                  url:
                    label: URL
                    type: text
              footerPages:
                label:
                  de: Verlinkte Seiten
                  en: Linked Pages
                type: pages
                image:
                  query: page.thumbnail.toFile
                  cover: true
                  back: white
                translate: false

      - width: 1/2
        sections:
          metaHeadline:
            type: fields
            fields:
              headlineMeta:
                label: SEO
                type: headline
          meta:
            extends: sections/meta
            type: fields
            fields:
              customTitle: false
              thumbnail:
                query: kirby.page("photography").files.template("image")
                uploads:
                  parent: kirby.page("photography")
                  template: image
