title:
  de: Seite
  en: Site

tabs:
  dashboard:
    label:
      de: Übersicht
      en: Dashboard
    icon: paragraph
    columns:
      - width: 2/3
        sections:
          articles:
            extends: sections/articles
            label:
              de: Artikel
              en: Articles
            layout: table
            columns:
              published:
                label:
                  de: Veröffentlicht
                  en: Published
                value: '{{ page.published.toDate("dd.MM.Y") }}'
                width: 1/4

      - width: 1/3
        sections:
          pages:
            type: pages
            label:
              de: Seiten
              en: Pages
            status: all
            create: default
            info: "/{{ page.slug }}"
            image:
              query: page.thumbnail.toFile
              cover: true
              back: "#89937A"

  settings:
    label:
      de: Einstellungen
      en: Settings
    icon: settings
    columns:
      - width: 1/2
        sections:
          content:
            type: fields
            fields:
              headlineContent:
                label:
                  de: Inhalt
                  en: Content
                type: headline
              popularArticles:
                label:
                  de: Beliebte Artikel
                  en: Popular Articles
                type: pages
                query: kirby.page("blog")
                image:
                  query: page.thumbnail.toFile
                  cover: true
                  back: white
                translate: false
              footerPages:
                label:
                  de: Fußzeilenlinks
                  en: Footer Pages
                type: pages
                image:
                  query: page.thumbnail.toFile
                  cover: true
                  back: white
                translate: false
              headlineAlgolia:
                label: Algolia
                type: headline
              algoliaIndex:
                label: johannschopplich.algolia-docsearch.index.start
                type: janitor
                command: "algolia-docsearch:index"

      - width: 1/2
        sections:
          metaHeadline:
            type: fields
            fields:
              headlineMeta:
                label: SEO
                type: headline
          meta:
            extends: sections/meta
            type: fields
            fields:
              customTitle: false
              thumbnail:
                query: kirby.page("photography").files.template("image")
                uploads:
                  parent: kirby.page("photography")
                  template: image
