title:
  de: Seite
  en: Site

buttons:
  - open
  - preview
  - copilot
  - languages

tabs:
  dashboard:
    label:
      de: Struktur
      en: Structure
    icon: sitemap
    columns:
      - width: 2/3
        sections:
          articles:
            extends: sections/articles
            label:
              de: Artikel
              en: Articles
            layout: table
            search: true
            columns:
              published:
                label:
                  de: Veröffentlicht
                  en: Published
                value: '{{ page.published.toDate("dd.MM.Y") }}'
                width: 1/4

      - width: 1/3
        sections:
          pages:
            type: pages
            label:
              de: Seiten
              en: Pages
            status: all
            create: default
            info: "/{{ page.slug }}"
            image:
              query: page.thumbnail.toFile
              cover: true
              back: "#67794b"

  content:
    label:
      de: Inhalt
      en: Content
    icon: layers
    columns:
      - width: 1/2
        sections:
          popularArticles:
            type: fields
            fields:
              popularArticles:
                label:
                  de: Beliebte Artikel
                  en: Popular Articles
                type: pages
                query: kirby.page("blog")
                image:
                  query: page.thumbnail.toFile
                  cover: true
                  back: white
                translate: false

      - width: 1/2
        sections:
          footer:
            type: fields
            fields:
              footerLinks:
                label: Links
                type: structure
                fields:
                  category:
                    label:
                      de: Kategorie
                      en: Category
                    type: text
                  title:
                    label:
                      de: Titel
                      en: Title
                    type: text
                  url:
                    label: URL
                    type: text
              footerPages:
                label:
                  de: Verlinkte Seiten
                  en: Linked Pages
                type: pages
                image:
                  query: page.thumbnail.toFile
                  cover: true
                  back: white
                translate: false

  seo:
    label: SEO
    icon: search
    sections:
      meta:
        type: fields
        fields:
          description:
            label:
              de: Beschreibung (Überschreiben)
              en: Description (Override)
            type: textarea
            buttons: false
            help:
              de: Eine kurze Beschreibung für Suchmaschinen.
              en: A short description for search engines.
          thumbnail:
            label:
              de: Vorschaubild
              en: Thumbnail
            type: files
            query: kirby.page("photography").files.template("image")
            uploads:
              parent: kirby.page("photography")
              template: image
            multiple: false
            translate: false
